# Generated by Django 4.2.2 on 2023-10-17 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questoes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questao",
            name="origem",
        ),
    ]
