# Generated by Django 4.2.2 on 2023-09-17 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
        ("questoes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=300)),
                ("compartilhado", models.BooleanField(default=False)),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
                ("questoes", models.ManyToManyField(to="questoes.questao")),
            ],
        ),
        migrations.CreateModel(
            name="SimuladoCompartilhado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "link",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tempo_de_prova", models.IntegerField(default=0)),
                ("qtd_tentativas", models.IntegerField(default=0)),
                (
                    "data_inicio",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("data_fim", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "simulado",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulados.simulado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespostaSimulado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "simulado_respondido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulados.simuladocompartilhado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespostaQuestaoSimulado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("resposta", models.CharField(max_length=1)),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questoes.questao",
                    ),
                ),
                (
                    "resposta_simulado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulados.respostasimulado",
                    ),
                ),
            ],
        ),
    ]
