# Generated by Django 4.2.2 on 2023-07-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('pagina_principal', '0007_delete_simulado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('questoes', models.ManyToManyField(to='pagina_principal.questao')),
            ],
        ),
    ]
