# Generated by Django 4.2.2 on 2023-07-26 13:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principal', '0007_delete_simulado'),
        ('usuarios', '0001_initial'),
        ('simulados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='compartilhado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='simulado',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.CreateModel(
            name='SimuladoCompartilhado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('simulado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simulados.simulado')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaSimulado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('simulado_respondido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulados.simuladocompartilhado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaQuestaoSimulado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resposta', models.CharField(max_length=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_principal.questao')),
                ('resposta_simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulados.respostasimulado')),
            ],
        ),
    ]
