# Generated by Django 4.2.2 on 2023-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0003_simuladocompartilhado_qtd_tentativas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuladocompartilhado',
            name='data_fim',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='simuladocompartilhado',
            name='data_inicio',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
