# Generated by Django 4.2.2 on 2023-07-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_assunto', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_questao', models.IntegerField(default=0)),
                ('tipo_questao', models.CharField(default='none', max_length=120)),
                ('curso', models.TextField(default='Não Cadastrado')),
                ('conteudo', models.TextField(default='none')),
                ('alternativa_a', models.TextField(default='none')),
                ('alternativa_b', models.TextField(default='none')),
                ('alternativa_c', models.TextField(default='none')),
                ('alternativa_d', models.TextField(default='none')),
                ('alternativa_e', models.TextField(default='none')),
                ('alternativa_correta', models.CharField(default='0', max_length=1)),
                ('assuntos', models.ManyToManyField(to='pagina_principal.assunto')),
            ],
        ),
    ]
