# Generated by Django 4.2.2 on 2023-07-04 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='conteudo',
            new_name='pergunta',
        ),
    ]
