# Generated by Django 4.2.2 on 2023-07-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principal', '0002_rename_conteudo_questao_pergunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questoes', models.ManyToManyField(to='pagina_principal.questao')),
            ],
        ),
    ]
