# Generated by Django 4.2.2 on 2023-07-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principal', '0003_simulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='titulo',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
