# Generated by Django 4.2.2 on 2023-07-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principal', '0004_simulado_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulado',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
