# Generated by Django 4.2.2 on 2023-07-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principal', '0006_remove_questao_n_questao_remove_questao_tipo_questao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Simulado',
        ),
    ]
