# Generated by Django 4.2.2 on 2023-07-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principal', '0007_delete_simulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='ano',
            field=models.BigIntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='origem',
            field=models.TextField(default='Outros'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_correta',
            field=models.CharField(max_length=1),
        ),
    ]
