# Generated by Django 4.2.2 on 2023-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
